apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  selector:
    app: helloapp
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: worldservice
spec:
  selector:
    app: worldapp
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
